### ISSUE TITLE
Puppet Forge 1.1.1, 1.1.0 are...nothing? Empty? Just the manifest

### ISSUE THREAD

**Issue by griggi-clarkson** [Chassis/puppet-wp#137]
Are [these](https://forge.puppet.com/modules/chassis/puppet_wp) intentionally just a bunch of empty folders? If so, why are they still posted on forge at all?

**Comment by BronsonQuick** [comment]
Hey @griggi-clarkson, that definitely wasn't intentional. That'll just be an oversight from me. This project is still used upstream in [Chassis core](https://github.com/Chassis/Chassis) as we bundle it as a submodule. I adopted this project and at looks like I've neglected how it's built and distributed upstream in Puppet Forge.

**Comment by BronsonQuick** [comment]
Hey @griggi-clarkson, I just added `metadata.json`, ran `pdk build` and I've published 1.2.0 on Puppet Forge so this should be resolved now.
